---
sudo: required

language: python
services:
  - docker

before_script:
  - pip install pyyaml
  - docker login -u $docker_user -p $docker_password

script:
  - bash test.sh
  - python generate.py

after_script:
  - docker logout

notifications:
  email: true
