---
sudo: required

language: python
services:
  - docker

before_script:
  - pip install -r requirements.txt --user $USER
  - docker login -u $docker_user -p $docker_password

jobs:
  include:
    - stage: tests
      script:
      - bash test.sh

    - stage: deploy
      script:
      - cd bin && python main.py

after_script:
  - docker logout

notifications:
  email: true





