---
sudo: required

language: python
services:
  - docker

script:
  - bash test.sh

jobs:
  include:
    - stage: test
      script:
      - bash test.sh

    - stage: deploy
      script:
      - python generate.py

notifications:
  email: true
